### ISSUE TITLE
why in_addr, out_addr, diff signals are of size  ADDRESS+1

### ISSUE THREAD

**Issue by abhisheietk** [abhisheietk/MyHDL_tutorial#1]
Why ADDRESS+1 bit length is taken for these variable pointers? Is it for signed representation?

**Comment by abhisheietk** [comment]
Actually a fifo is of definite size. And it works as a ring that means write pointer goes to zero after value (2**ADDRESS). now this happens inherently if pointer bit size is ADDRESS.

But their is a problem... Lets assume ADDRESS = 8 so total register count is 256. Think of a case where 
in_addr = 250 , out_addr = 240 further read and writes are happening simultaneously. 
so after 5 read and write in_addr = 255 , out_addr = 240
further one more new write will result into
in_addr = 256 => 0 , out_addr = 240
now this will fail the logic where we want in_addr to be always greater then out_addr

on other hand if you take in_adder, out_adder sizes ADDRESS+1 bits then 
in_addr = 256 (not equal to 0) , out_addr = 240

and when out_addr crosses 255 then set msb of both in_addr and  out_addr to zero
in_addr = 260 [1 0000 0100], out_addr = 256 [1 0000 0000]
=> in_addr = 4 [0 0000 0100], out_addr = 0 [0 0000 0000]

Probably I missed this last logic in my code.

**Comment by Shilpimish** [comment]
'now this will fail the logic where we want in_addr to be always greater then out_addr' 
Why do we want this? In a cyclic queue event with a cushion of 8, we can implement it.

**Comment by abhisheietk** [comment]
Elaborate with some example case. According to me  in_addr will always be greater then out_addr.

**Comment by Shilpimish** [comment]
I mean since its cyclic and the in_addr, out_addr (if suppose its of 8 bit length) would wrap around after 255(11111111). So Its possible in_addr is then at say index 10 and out_addr at 250 (8 bit Address bit).

And even in this condition we can implement the overflow, underflow check. Isn't it? 
==========

Okay, I got this too, in case of 9 bit.
[
in_addr = 260 [1 0000 0100], out_addr = 256 [1 0000 0000]
=> in_addr = 4 [0 0000 0100], out_addr = 0 [0 0000 0000]
]

But this logic was not implemented in your code. Is it? We are simply slicing and using LSB 8 bits for read and write.

**Comment by abhisheietk** [comment]
Yes you are correct. Now can you modify it to include this case.
